#Server Configuration    
server:
  port: 9700
# App  Configuration   
spring:     
  application:
   name: ORDER-HISTROY  
 #Service Config   
capstone:
  orderservice:
           url: ${ORDER_URI}   
  cartservice:
          url: ${CART_URI}              
         