#Eureka Client Details 
eureka:
 client:
   register-with-eureka: true
   fetch-registry : true
   service-url:
     defaultZone: http://localhost:8761/eureka
#Server Configuration    
server:
  port: 9700
# App and DB Configuration   
spring:     
  application:
   name: ORDER-HISTROY  
 #Service Config   
capstone:
  orderservice:
           url: https://ascend-team08.free.beeceptor.com/order/
  cartservice:
          url: https://ascend-team08.free.beeceptor.com/cart/
          path: fetchCartDetails/user/ 